[package]
name = "near-synth-bm"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true


[dependencies]
anyhow.workspace = true 
clap = { workspace = true, features = ["derive"] }
env_logger.workspace = true
log.workspace = true
near-crypto = "0.27"
near-jsonrpc-client = "0.14.0"
near-jsonrpc-primitives = "0.27"
near-primitives = "0.27"
rand.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tracing = { workspace = true, features = ["std"] }
